### PR TITLE
Allows to use a pkcs12 or pem certificate, adds examples and update build settings

### PR DESCRIPTION
**Pull request by efremmoraes**
Hi,

Hope this PR could be merged. You would only need to change some links on the README.md

Thanks for the project!

### CODE REVIEW

**Comment by Maks3w** [comment]
@efremmoraes Thanks for the proposal.

a) When you intent to push a feature to upstream provider try to be more friendly and don't push with your own URLs.

b) All the staff about PKCS#12 is out of the scope of to have a minimal and safe interface.
Minimal because is easy of understand.
Safe because doesn't do magical things like guess if is data or file path.

c) The proposed new argument `$appendToNode` is interesting and could be ok with the scope of the project. Unfortunately the examples does not show any user case for that argument neither reference to any part of the XMLDsig standard. Could you detail what is the user case?

**Comment by efremmoraes** [comment]
a) Sorry about the URL. It was not my intention to be unfriendly. I've never created a PR of this size nor merged one before. So I thought that would be a cleaner way on the merging process to do this instead of: change url, PR, then change back whenever I needed to change something in the repo.

b) Giving some thought on this now, I tend to agree with you. The idea initially was to makes things easier to some people get started without greater knowledge on openssl or certificates formats. The `setCertificate` could be only x509.

c) The idea here is to be able to reuse the `XmlseclibsAdapter` class. For instance, implementing the XAdEs: http://www.w3.org/TR/XAdES/ without messing with the code to create `CounterSignatures`. I will probably need to implement this in the near future.

So, besides the changed urls on the a) do you think it's better to remove pkcs#12 support?

**Comment by Maks3w** [comment]
If you split the PR in more narrow features then I'll merge more things.

* The stuff about Travis-CI
* Examples but as the code is now (without the changes introduced in the interface)
* PKCS#12
  - implemented only in the final class (don't touch the interface)
  - Only receive the file, and don't magic guess if is file path or file content)
  - Split in two methods. `setPrivateAndPublicKeysFromX509($certificate)` and `setPrivateAndPublicKeysFromPkcs12($fileContents)`
  - PKCS#12 bundle file with the password "Unsecure"
* XAdES feature
* `verify()` cloned bug? I don't see in the unit tests why is necessary clone the data.

Please follow PSR-1 coding style guidelines.

**Comment by efremmoraes** [comment]
Nice, thanks for taking the time to improve things.

Next time I work on this project I'll open some PR then.

**Pull request closed without merging**
